baseURL = "https://kerem-orhan.github.io/pharmacutecials/"
languageCode = "en-us"
title = "Pharmaceuticals"
theme = "PaperMod"
paginate = 6

[params]
  description = "Pharmaceutical information and resources"
  ShowReadingTime = true
  ShowPostNavLinks = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "About"
url = "/about/"
weight = 2
[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 3
